export const NOT_FOUND = 404;
export const BAD_REQUEST = 400;
export const INTERNAL_SERVER_ERROR = 500;

export const ERROR_CODES = {
  CUSTOMER_NOT_FOUND_ERROR: 'CUSTOMER_NOT_FOUND_ERROR',
  CUSTOMER_BAD_REQUEST_ERROR: 'CUSTOMER_BAD_REQUEST_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};